### ISSUE TITLE
%20 added at the end of URLs

### ISSUE THREAD

**Issue by SyrianSpock** [YoussefRaafatNasry/portfolYOU#25] opened 2020-03-02 18:04 UTC
I noticed that %20 are added at the end of URLs, like http://localhost:8080/projects%20 whereas http://localhost:8080/projects works do you have a workaround or fix for this? TY
Other than that, very nice theme, great work!

**Comment by YoussefRaafatNasry** [comment] 2020-03-03 08:46
Duplicate of #14, #15

**Comment by YoussefRaafatNasry** [comment] 2020-03-03 08:47
Make sure you are using the latest version of portfolYOU.
Everything seems to be working fine here

![image](https://user-images.githubusercontent.com/41103290/75757970-ff8b6300-5d3b-11ea-867b-5ba5b688bd32.png)

If the issue still exists, please reopen the issue.

**Closed by YoussefRaafatNasry** 2020-03-03 08:46 UTC

**Comment by SyrianSpock** [comment] 2020-03-03 14:04
Indeed latest version works well thanks, except for some plugins
```
Liquid Exception: Liquid syntax error (/site/_includes/elements/github-edit-footer.html line 3): Unknown tag 'github_edit_link' included in docs/documentation/docs.md
```
```
Liquid Exception: Liquid syntax error (line 44): Unknown tag 'gist' in /site/docs/_posts/2018-12-10-clean-coding.md
```

**Comment by YoussefRaafatNasry** [comment] 2020-03-03 18:32
1. Make sure you are using `github-pages` gem in your [`Gemfile`](https://github.com/YoussefRaafatNasry/portfolYOU/blob/34679248199dcb7b60654defffe28cac6bbbe3ea/docs/Gemfile#L3). 
1. Run `bundle install`.
1. Update `repository` tag in [`_config.yml`](https://github.com/YoussefRaafatNasry/portfolYOU/blob/34679248199dcb7b60654defffe28cac6bbbe3ea/docs/_config.yml#L8) to match the GitHub repository of your source code.
