### ISSUE TITLE
Creating two project-like pages

### ISSUE THREAD

**Issue by jasoncwong** [YoussefRaafatNasry/portfolYOU#73] opened 2021-05-19 04:46 UTC
New here - could anyone walk me through how to create multiple tabs that resemble the blog or projects? just copying the file structures does not seem to work... I see a few closed issues that did not reveal how to do so. Thanks in advance!

**Comment by YoussefRaafatNasry** [comment] 2021-05-19 08:26
duplicate of #49

**Closed by YoussefRaafatNasry** 2021-05-19 08:26 UTC
Labels: duplicate
